/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as credLinkSol from "./CredLink.sol";
export * as interfaces from "./interfaces";
export * as lib from "./lib";
export { CredLinkToken__factory } from "./CredLinkToken__factory";
