/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as credLinkSol from "./CredLink.sol";
export type { credLinkSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as lib from "./lib";
export type { lib };
export type { CredLinkToken } from "./CredLinkToken";
